version: "3.5" 

services:
  keyrock:
    image: fiware/idm:7.8.1
    container_name: fiware-keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - mysql-db
    ports:
      - '6000:6000'
      - '443:443'
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=mysql-db
      - IDM_HOST=http://localhost:6000
      - IDM_PORT=6000
      - IDM_DB_PASS=secret
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=1234
  mysql-db:
    restart: always
    image: mysql:5.7
    hostname: mysql-db
    container_name: db-mysql
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      - 'MYSQL_ROOT_PASSWORD=secret'
      - 'MYSQL_ROOT_HOST=172.18.1.5'
    volumes:
      - mysql-db:/var/lib/mysql
  orion:
    image: fiware/orion
    ports:
      - "1026:1026"
    depends_on:
      - mongo
    command: -dbhost mongo

  mongo:
    image: mongo:4.4
    command: --nojournal

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24

volumes:
  mysql-db: ~